# Profile information
name: Reanimate
title: Reanimate - Recovering Media Histories
description: > # this means to ignore newlines until "baseurl:"
  Reanimate is an intersectional feminist publishing collective that recovers and publishes digital editions of writing by women in media.
permalink: ':title/'
baseurl: "/fresh" # the subpath of your site, e.g. /blog
url: "http://roopikarisam.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
